version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing app dependencies...
      - npm install

  build:
    commands:
      - echo Building static site...
      - npm run build

  post_build:
    commands:
      - echo Build complete!

artifacts:
  files:
    - ./build/**/*
